<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Leave;

class LeaveSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array (
            0 => 
            array (
              0 => '59',
              1 => '3',
              2 => '1',
              3 => '2022-08-11',
              4 => '2022-08-13',
              5 => '24',
              6 => 'I am writing to document my absence due to illness today. I was unable to report to work due to an acute attack of food poisoning. Please see the attached report of my treatment at Urgent Care in your email.',
              7 => '2',
              8 => '1',
              9 => '2022-08-11',
              10 => '2022-08-11',
            ),
            1 => 
            array (
              0 => '65',
              1 => '1',
              2 => '1',
              3 => '2020-03-27',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '0',
              9 => '2020-03-27',
              10 => '2020-03-27',
            ),
            2 => 
            array (
              0 => '53',
              1 => '1',
              2 => '1',
              3 => '2022-01-04',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '0',
              9 => '2022-01-04',
              10 => '2022-01-04',
            ),
            3 => 
            array (
              0 => '24',
              1 => '1',
              2 => '1',
              3 => '2022-11-14',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '0',
              9 => '2022-11-14',
              10 => '2022-11-14',
            ),
            4 => 
            array (
              0 => '19',
              1 => '2',
              2 => '3',
              3 => '2022-02-27',
              4 => '',
              5 => '4',
              6 => 'I am writing this email to let you know that I will require a half day leave today as I need to visit the bank. My ATM card seems to have stopped working, and I need to visit the bank to sort out the issues',
              7 => '3',
              8 => '1',
              9 => '2022-02-27',
              10 => '2022-02-27',
            ),
            5 => 
            array (
              0 => '23',
              1 => '1',
              2 => '1',
              3 => '2020-03-06',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '1',
              9 => '2020-03-06',
              10 => '2020-03-06',
            ),
            6 => 
            array (
              0 => '54',
              1 => '3',
              2 => '2',
              3 => '2022-02-21',
              4 => '2022-02-25',
              5 => '40',
              6 => 'I would like to formally request a 1 week leave of absence for personal reasons. If possible, I would like the leave from work to begin on May 21, 2022, with a return date of May 25, 2022.If approved, I will be staying with family in Laguna during this time period, and I would be glad to assist with any questions via email or phone whenever possible.',
              7 => '2',
              8 => '0',
              9 => '2022-02-21',
              10 => '2022-02-21',
            ),
            7 => 
            array (
              0 => '20',
              1 => '1',
              2 => '3',
              3 => '2020-09-18',
              4 => '',
              5 => '8',
              6 => 'I am writing to you to let you know that I have an important personal matter to attend at my hometown due to which I will not be able to come to the office today.',
              7 => '2',
              8 => '1',
              9 => '2020-09-18',
              10 => '2020-09-18',
            ),
            8 => 
            array (
              0 => '66',
              1 => '1',
              2 => '1',
              3 => '2020-03-19',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '0',
              9 => '2020-03-19',
              10 => '2020-03-19',
            ),
            9 => 
            array (
              0 => '24',
              1 => '2',
              2 => '3',
              3 => '2020-12-09',
              4 => '',
              5 => '4',
              6 => 'This is to inform you that I will not be able to come to work on time on today as I have an appointment with the dentist.',
              7 => '2',
              8 => '1',
              9 => '2020-12-09',
              10 => '2020-12-09',
            ),
            10 => 
            array (
              0 => '29',
              1 => '1',
              2 => '3',
              3 => '2020-07-15',
              4 => '',
              5 => '8',
              6 => 'I am writing to you to let you know that I have an important personal matter to attend at my hometown due to which I will not be able to come to the office today.',
              7 => '2',
              8 => '0',
              9 => '2020-07-15',
              10 => '2020-07-15',
            ),
            11 => 
            array (
              0 => '56',
              1 => '1',
              2 => '1',
              3 => '2020-12-15',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '0',
              9 => '2020-12-15',
              10 => '2020-12-15',
            ),
            12 => 
            array (
              0 => '22',
              1 => '1',
              2 => '1',
              3 => '2020-04-06',
              4 => '',
              5 => '8',
              6 => 'Please accept this written notification of my absence today. I am unable to attend work due to sickness.',
              7 => '2',
              8 => '0',
              9 => '2020-04-06',
              10 => '2020-04-06',
            ),
            13 => 
            array (
              0 => '28',
              1 => '2',
              2 => '3',
              3 => '2020-01-24',
              4 => '',
              5 => '4',
              6 => 'I am writing this email to let you know that I will require a half day leave today as I need to visit the bank. My ATM card seems to have stopped working, and I need to visit the bank to sort out the issues',
              7 => '3',
              8 => '0',
              9 => '2020-01-24',
              10 => '2020-01-24',
            ),
            14 => 
            array (
              0 => '58',
              1 => '1',
              2 => '3',
              3 => '2022-05-11',
              4 => '',
              5 => '8',
              6 => 'I wish to inform you that I have to go with my younger daughter to her school for the Annual Day function tomorrow. As the function will run from morning to evening, I would not be able to attend the office.',
              7 => '1',
              8 => '0',
              9 => '2022-05-11',
              10 => '2022-05-11',
            ),
            15 => 
            array (
              0 => '19',
              1 => '1',
              2 => '1',
              3 => '2022-04-01',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '1',
              9 => '2022-04-01',
              10 => '2022-04-01',
            ),
            16 => 
            array (
              0 => '27',
              1 => '3',
              2 => '1',
              3 => '2022-04-27',
              4 => '2022-05-11',
              5 => '80',
              6 => 'I won’t be able to report to work today because I’m under the weather and have a cold. I went to the emergency room last night and the doctor confirmed that I\'ve got covid. The doctor prescribed 2 weeks as I am contagious, so I asked my co-worker to take over my workload this afternoon. They\'ll also handle my pending tasks while I\'m away. I\'ll be available via email for your urgent needs.I’ve also attached the doctor’s note and send it via email. Thank you.',
              7 => '2',
              8 => '1',
              9 => '2022-04-27',
              10 => '2022-04-27',
            ),
            17 => 
            array (
              0 => '67',
              1 => '1',
              2 => '1',
              3 => '2022-03-22',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '0',
              9 => '2022-03-22',
              10 => '2022-03-22',
            ),
            18 => 
            array (
              0 => '21',
              1 => '3',
              2 => '1',
              3 => '2022-01-10',
              4 => '2022-01-21',
              5 => '80',
              6 => 'I am writing to request you for a leave of 2 weeks from Jan 10, 2022 to Jan 21, 2022 since I have to attend to a medical emergency of a close relative. As the relative is situated in Uttrakhand, I will have to be away for 10 days. I will resume work from Jan 21, 2022.',
              7 => '2',
              8 => '0',
              9 => '2022-01-10',
              10 => '2022-01-10',
            ),
            19 => 
            array (
              0 => '55',
              1 => '1',
              2 => '3',
              3 => '2022-02-25',
              4 => '',
              5 => '8',
              6 => 'I would like to mention that I have to attend my niece’s engagement ceremony today. I would be grateful if you can approve my leave request for the aforementioned period.Hoping to receive a positive response from you.',
              7 => '2',
              8 => '0',
              9 => '2022-02-25',
              10 => '2022-02-25',
            ),
            20 => 
            array (
              0 => '26',
              1 => '1',
              2 => '1',
              3 => '2020-01-15',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '1',
              9 => '2020-01-15',
              10 => '2020-01-15',
            ),
            21 => 
            array (
              0 => '68',
              1 => '2',
              2 => '3',
              3 => '2022-10-11',
              4 => '',
              5 => '4',
              6 => 'This application is to request you with immense reverence that, I am in need of half-day leave tomorrow. I have to visit my research supervisor to discuss important work related to the final defense of my thesis. For this, I’ll have to leave by 12 am. Kindly sanction me half day leave. This would serve a great favor. I’ll be obliged.',
              7 => '2',
              8 => '0',
              9 => '2022-10-11',
              10 => '2022-10-11',
            ),
            22 => 
            array (
              0 => '62',
              1 => '1',
              2 => '1',
              3 => '2022-05-15',
              4 => '',
              5 => '8',
              6 => 'Please accept this written notification of my absence today. I am unable to attend work due to sickness.',
              7 => '1',
              8 => '0',
              9 => '2022-05-15',
              10 => '2022-05-15',
            ),
            23 => 
            array (
              0 => '25',
              1 => '1',
              2 => '1',
              3 => '2020-03-03',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '0',
              9 => '2020-03-03',
              10 => '2020-03-03',
            ),
            24 => 
            array (
              0 => '57',
              1 => '3',
              2 => '1',
              3 => '2022-11-15',
              4 => '2022-11-17',
              5 => '24',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '2',
              8 => '0',
              9 => '2022-11-15',
              10 => '2022-11-15',
            ),
            25 => 
            array (
              0 => '1',
              1 => '1',
              2 => '1',
              3 => '2022-06-28',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '3',
              8 => '0',
              9 => '2022-06-28',
              10 => '2022-06-28',
            ),
            26 => 
            array (
              0 => '57',
              1 => '1',
              2 => '1',
              3 => '2020-06-26',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '1',
              9 => '2020-06-26',
              10 => '2020-06-26',
            ),
            27 => 
            array (
              0 => '19',
              1 => '2',
              2 => '3',
              3 => '2022-05-09',
              4 => '',
              5 => '4',
              6 => 'This is to inform you that I will not be able to come to work on time on today as I have an appointment with the dentist.',
              7 => '1',
              8 => '0',
              9 => '2022-05-09',
              10 => '2022-05-09',
            ),
            28 => 
            array (
              0 => '29',
              1 => '1',
              2 => '1',
              3 => '2020-10-02',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '0',
              9 => '2020-10-02',
              10 => '2020-10-02',
            ),
            29 => 
            array (
              0 => '55',
              1 => '1',
              2 => '1',
              3 => '2022-04-14',
              4 => '',
              5 => '8',
              6 => 'Please accept this written notification of my absence today. I am unable to attend work due to sickness.',
              7 => '2',
              8 => '0',
              9 => '2022-04-14',
              10 => '2022-04-14',
            ),
            30 => 
            array (
              0 => '63',
              1 => '3',
              2 => '2',
              3 => '2022-08-17',
              4 => '2022-08-24',
              5 => '48',
              6 => 'I would like to formally request a 1 week leave of absence for personal reasons. If possible, I would like the leave from work to begin on August 17, 2022, with a return date of August 25, 2022.',
              7 => '2',
              8 => '0',
              9 => '2022-08-17',
              10 => '2022-08-17',
            ),
            31 => 
            array (
              0 => '22',
              1 => '1',
              2 => '1',
              3 => '2020-07-07',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '2',
              8 => '0',
              9 => '2020-07-07',
              10 => '2020-07-07',
            ),
            32 => 
            array (
              0 => '64',
              1 => '2',
              2 => '3',
              3 => '2020-07-25',
              4 => '',
              5 => '4',
              6 => 'This application is to request you with immense reverence that, I am in need of half-day leave tomorrow. I have to visit my research supervisor to discuss important work related to the final defense of my thesis. For this, I’ll have to leave by 12 am. Kindly sanction me half day leave. This would serve a great favor. I’ll be obliged.',
              7 => '2',
              8 => '0',
              9 => '2020-07-25',
              10 => '2020-07-25',
            ),
            33 => 
            array (
              0 => '21',
              1 => '2',
              2 => '3',
              3 => '2020-08-17',
              4 => '',
              5 => '4',
              6 => 'I would like to notify you that today, I have to attend an annual Parent Teacher Meeting of my daughter. As her father is not well so I have to go there. It is just a matter of one day. Kindly grant me leave for half-day after 1 pm for today. It would be really grateful to you.',
              7 => '2',
              8 => '0',
              9 => '2020-08-17',
              10 => '2020-08-17',
            ),
            34 => 
            array (
              0 => '26',
              1 => '1',
              2 => '1',
              3 => '2020-06-04',
              4 => '',
              5 => '8',
              6 => 'Sorry to inform you that I can’t make it to work today, as I’ve come down with a stomach ache. I\'ll be available to answer emails if you need urgent help, but my assistant will handle my workload today to ensure all deadlines are met.',
              7 => '2',
              8 => '0',
              9 => '2020-06-04',
              10 => '2020-06-04',
            ),
            35 => 
            array (
              0 => '20',
              1 => '1',
              2 => '1',
              3 => '2020-06-17',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '0',
              9 => '2020-06-17',
              10 => '2020-06-17',
            ),
            36 => 
            array (
              0 => '25',
              1 => '1',
              2 => '1',
              3 => '2022-04-14',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '0',
              9 => '2022-04-14',
              10 => '2022-04-14',
            ),
            37 => 
            array (
              0 => '60',
              1 => '1',
              2 => '1',
              3 => '2022-11-25',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '2',
              8 => '0',
              9 => '2022-11-25',
              10 => '2022-11-25',
            ),
            38 => 
            array (
              0 => '27',
              1 => '1',
              2 => '1',
              3 => '2022-09-27',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '3',
              8 => '1',
              9 => '2022-09-27',
              10 => '2022-09-27',
            ),
            39 => 
            array (
              0 => '61',
              1 => '1',
              2 => '1',
              3 => '2022-01-11',
              4 => '',
              5 => '8',
              6 => 'I\'m writing this to let you know that I need to take sick leave because of severe migraines. Per my physician\'s orders, I will need to remain off work today.',
              7 => '2',
              8 => '1',
              9 => '2022-01-11',
              10 => '2022-01-11',
            ),
            40 => 
            array (
              0 => '28',
              1 => '3',
              2 => '2',
              3 => '2020-08-14',
              4 => '2020-08-21',
              5 => '48',
              6 => 'I would like to formally request a 1 week leave of absence for personal reasons. If possible, I would like the leave from work to begin on August 14, 2020, with a return date of August 21, 2020.',
              7 => '2',
              8 => '1',
              9 => '2020-08-14',
              10 => '2020-08-14',
            ),
            41 => 
            array (
              0 => '24',
              1 => '1',
              2 => '1',
              3 => '2022-07-28',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '2',
              8 => '0',
              9 => '2022-07-28',
              10 => '2022-07-28',
            ),
            42 => 
            array (
              0 => '53',
              1 => '2',
              2 => '3',
              3 => '2022-05-10',
              4 => '',
              5 => '4',
              6 => 'Sorry to inform you that I will need a half day leave today as my daughter has fallen ill. I received a call from her school, requesting me to go and pick her up as soon as possible. Since I will need to take her to the doctor, I will not be able to make it back to the office on time. I have emailed you the work plan so that the project work will not get disrupted during my absence.',
              7 => '2',
              8 => '0',
              9 => '2022-05-10',
              10 => '2022-05-10',
            ),
            43 => 
            array (
              0 => '23',
              1 => '1',
              2 => '1',
              3 => '2020-12-24',
              4 => '',
              5 => '8',
              6 => 'Please accept this written notification of my absence today. I am unable to attend work due to sickness.',
              7 => '2',
              8 => '1',
              9 => '2020-12-24',
              10 => '2020-12-24',
            ),
            44 => 
            array (
              0 => '54',
              1 => '2',
              2 => '3',
              3 => '2022-05-07',
              4 => '',
              5 => '4',
              6 => 'I would like to state that I want a few hours of the work-day off because of personal reasons. I am a very regular employee and such a nuisance has not occurred before. It so appears that my mother is traveling to see me and I have to receive her at the airport since he cannot manage to get by on his personal due to the fact that he has nevermore been here before. There is no one else on whom I could rely on my time of need. I would be thankful if you allow me to leave the office after lunch break tomorrow, 24th February 2020.I ensure you that my tasks for the day will be finished by then and it will not cause delays or negligence at work.',
              7 => '2',
              8 => '0',
              9 => '2022-05-07',
              10 => '2022-05-07',
            ),
            45 => 
            array (
              0 => '56',
              1 => '1',
              2 => '1',
              3 => '2020-09-10',
              4 => '',
              5 => '8',
              6 => 'Sorry, but I can’t make it to work today. I\'ve got a cold today, so I’m going to take the day off. I’ll be available to answer emails and calls.',
              7 => '2',
              8 => '0',
              9 => '2020-09-10',
              10 => '2020-09-10',
            ),
            46 => 
            array (
              0 => '64',
              1 => '1',
              2 => '1',
              3 => '2020-08-25',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '2',
              8 => '0',
              9 => '2020-08-25',
              10 => '2020-08-25',
            ),
            47 => 
            array (
              0 => '29',
              1 => '1',
              2 => '1',
              3 => '2022-01-29',
              4 => '',
              5 => '8',
              6 => 'Please accept this written notification of my absence today. I am unable to attend work due to sickness.',
              7 => '2',
              8 => '0',
              9 => '2022-01-29',
              10 => '2022-01-29',
            ),
            48 => 
            array (
              0 => '66',
              1 => '1',
              2 => '1',
              3 => '2022-01-03',
              4 => '',
              5 => '8',
              6 => 'I\'ve included a letter from my doctor to confirm that I need to take that time off to fully recover. I apologize for any inconvenience that my absence from work may cause. I do intend to periodically check my email and work on some projects. When I return to work, I will do my best to catch up on all work I missed while I was on leave.',
              7 => '2',
              8 => '1',
              9 => '2022-01-03',
              10 => '2022-01-03',
            ),
            49 => 
            array (
              0 => '68',
              1 => '3',
              2 => '1',
              3 => '2022-05-20',
              4 => '2022-05-28',
              5 => '56',
              6 => 'I am writing this letter to inform you that I need to take sick leave from work. I will need to remain off work until May 28, 2022. I\'ve included a letter from my doctor to confirm that I need to take that amount of time off to fully recover.',
              7 => '2',
              8 => '0',
              9 => '2022-05-20',
              10 => '2022-05-20',
            ),
        );

        foreach($data as $value) 
        {
            $new_leave = new Leave;
            $new_leave->user_id = $value[0];
            $new_leave->type_id = $value[1];
            $new_leave->leave_type_id = $value[2];
            $new_leave->start_date = $value[3];
            if($value[4] != '') {
                $new_leave->end_date = $value[4];
            }
            $new_leave->hours_duration = $value[5];
            $new_leave->reason = $value[6];
            $new_leave->status = $value[7];
            $new_leave->is_paid = $value[8];
            $new_leave->created_at = $value[9];
            $new_leave->updated_at = $value[10];
            $new_leave->save();
        }

    }
}
