<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use App\Models\User;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array (
            0 => 
            array (
              0 => 'EMAIL',
              1 => 'LAST',
              2 => 'FIRST',
              3 => 'MIDDLE',
              4 => 'CODE',
              5 => 'PHONE #',
              6 => 'GENDER',
              7 => 'MARITAL STATUS',
              8 => 'NATIONALITY',
              9 => 'EMPLOYMENT STATUS',
              10 => 'IS PAID HOLIDAYS',
              11 => 'IS TAX EXEMPTED',
              12 => 'FREQUENCY ID',
              13 => 'JOB TITLE',
            ),
            1 => 
            array (
              0 => 'gabriellegallego@gmail.com',
              1 => 'Gallego',
              2 => 'Gabrielle',
              3 => 'Perez',
              4 => '2020-0002',
              5 => '09612212222',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            2 => 
            array (
              0 => 'gezrylclarizg@gmail.com',
              1 => 'Beato',
              2 => 'Gezryl',
              3 => 'Garcia',
              4 => '2020-0003',
              5 => '09299619549',
              6 => 'F',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            3 => 
            array (
              0 => 'calaub@hotmail.com',
              1 => 'Calderon',
              2 => 'Aubrey',
              3 => 'Gilla',
              4 => '2020-0004',
              5 => '09122354987',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            4 => 
            array (
              0 => 'bhoyetcartagena@hotmail.com',
              1 => 'Cartagena',
              2 => 'Bhoyeth',
              3 => 'De Venecia',
              4 => '2020-0005',
              5 => '09152846647',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            5 => 
            array (
              0 => 'alonecarol@hotmail.com',
              1 => 'Alonte',
              2 => 'Carol',
              3 => 'Cayetano',
              4 => '2020-0006',
              5 => '09586475895',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '11',
            ),
            6 => 
            array (
              0 => 'dugongpuzon@hotmail.com',
              1 => 'Puzon',
              2 => 'Dugong',
              3 => 'Cartagena',
              4 => '2020-0007',
              5 => '09547896548',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '5',
            ),
            7 => 
            array (
              0 => 'extonarcillas@hotmail.com',
              1 => 'Arcillas',
              2 => 'Exton',
              3 => 'Diliman',
              4 => '2020-0008',
              5 => '09547896546',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '5',
            ),
            8 => 
            array (
              0 => 'fredgomez@hotmail.com',
              1 => 'Gomez',
              2 => 'Fred',
              3 => 'Reyes',
              4 => '2020-0009',
              5 => '09565468795',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '5',
            ),
            9 => 
            array (
              0 => 'galehernandez@hotmail.com',
              1 => 'Hernandez',
              2 => 'Gale',
              3 => 'Ramos',
              4 => '2020-0010',
              5 => '09568785452',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            10 => 
            array (
              0 => 'belardehaley@hotmail.com',
              1 => 'Belarde',
              2 => 'Haley',
              3 => 'Mendoza',
              4 => '2020-0011',
              5 => '09482136549',
              6 => 'F',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            11 => 
            array (
              0 => 'acostairish@hotmail.com',
              1 => 'Acosta',
              2 => 'Irish',
              3 => 'Santos',
              4 => '2020-0012',
              5 => '09421356589',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            12 => 
            array (
              0 => 'masaredojhuney@hotmail.com',
              1 => 'Masaredo',
              2 => 'Jhuney',
              3 => 'Flores',
              4 => '2020-0013',
              5 => '09541252563',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            13 => 
            array (
              0 => 'marcoskiko@hotmail.com',
              1 => 'Jimenez',
              2 => 'Kiko',
              3 => 'Gonzales',
              4 => '2020-0014',
              5 => '09123652587',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            14 => 
            array (
              0 => 'robredosimon@hotmail.com',
              1 => 'Lim',
              2 => 'Simon',
              3 => 'Bautista',
              4 => '2020-0015',
              5 => '09652321587',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '11',
            ),
            15 => 
            array (
              0 => 'garciamary@hotmail.com',
              1 => 'Garcia',
              2 => 'Mary',
              3 => 'Villanueva',
              4 => '2020-0016',
              5 => '09154787456',
              6 => 'F',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '11',
            ),
            16 => 
            array (
              0 => 'pereznino@hotmail.com',
              1 => 'Perez',
              2 => 'Nino',
              3 => 'Fernandez',
              4 => '2020-0017',
              5 => '09654584632',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '11',
            ),
            17 => 
            array (
              0 => 'roblesoliver@hotmail.com',
              1 => 'Robles',
              2 => 'Oliver',
              3 => 'Cruz',
              4 => '2020-0018',
              5 => '09352156548',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '11',
            ),
            18 => 
            array (
              0 => 'penaphilip@hotmail.com',
              1 => 'Pena',
              2 => 'Philip',
              3 => 'De Guzman',
              4 => '2020-0019',
              5 => '09652351547',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            19 => 
            array (
              0 => 'riveraqueenie@hotmail.com',
              1 => 'Pascual',
              2 => 'Queenie',
              3 => 'Lopez',
              4 => '2020-0020',
              5 => '09485654875',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            20 => 
            array (
              0 => 'barriaronnie@hotmail.com',
              1 => 'Barria',
              2 => 'Ronnie',
              3 => 'Castillo',
              4 => '2020-0021',
              5 => '09652135852',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            21 => 
            array (
              0 => 'bautistajames@hotmail.com',
              1 => 'Bautista',
              2 => 'James',
              3 => 'Francisco',
              4 => '2020-0022',
              5 => '09655485555',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '1',
            ),
            22 => 
            array (
              0 => 'barrinuevotroy@hotmail.com',
              1 => 'Barrinuevo',
              2 => 'Troy',
              3 => 'Rivera',
              4 => '2020-0023',
              5 => '09467542154',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '2',
            ),
            23 => 
            array (
              0 => 'crisostomoroy@hotmail.com',
              1 => 'Crisostomo',
              2 => 'Roy',
              3 => 'Aquino',
              4 => '2020-0024',
              5 => '09466532643',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '3',
            ),
            24 => 
            array (
              0 => 'bayolawally@hotmail.com',
              1 => 'Bayola',
              2 => 'Wally',
              3 => 'Castro',
              4 => '2020-0025',
              5 => '09478756545',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '1',
            ),
            25 => 
            array (
              0 => 'ibarraxyrine@hotmail.com',
              1 => 'Sarmiento',
              2 => 'Xyrine',
              3 => 'Sanchez',
              4 => '2020-0026',
              5 => '09523212526',
              6 => 'F',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '2',
            ),
            26 => 
            array (
              0 => 'bernardoandoy@hotmail.com',
              1 => 'Bernardo',
              2 => 'Andoy',
              3 => 'Torres',
              4 => '2020-0027',
              5 => '09875896585',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '3',
            ),
            27 => 
            array (
              0 => 'manalozacari@hotmail.com',
              1 => 'Manalo',
              2 => 'Zacari',
              3 => 'De Leon',
              4 => '2020-0028',
              5 => '09125125515',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '1',
            ),
            28 => 
            array (
              0 => 'sottoanna@hotmail.com',
              1 => 'Sotto',
              2 => 'Anna',
              3 => 'Domingo',
              4 => '2020-0029',
              5 => '09656585215',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '2',
            ),
            29 => 
            array (
              0 => 'hilarioberto@hotmail.com',
              1 => 'Hilario',
              2 => 'Berto',
              3 => 'Martinez',
              4 => '2020-0030',
              5 => '09655452528',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '3',
            ),
            30 => 
            array (
              0 => 'navarrocris@hotmail.com',
              1 => 'Navarro',
              2 => 'Cris',
              3 => 'Rodriguez',
              4 => '2020-0031',
              5 => '09652363214',
              6 => 'F',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '1',
            ),
            31 => 
            array (
              0 => 'alcantaracarlo@hotmail.com',
              1 => 'Alcantara',
              2 => 'Carlo',
              3 => 'Santiago',
              4 => '2020-0032',
              5 => '09875423698',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '2',
            ),
            32 => 
            array (
              0 => 'umalidave@hotmail.com',
              1 => 'Umali',
              2 => 'Dave',
              3 => 'Soriano',
              4 => '2020-0033',
              5 => '09544752321',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '3',
            ),
            33 => 
            array (
              0 => 'bartolomedonna@hotmail.com',
              1 => 'Bartolome',
              2 => 'Donna',
              3 => 'Delos Santos',
              4 => '2020-0034',
              5 => '09362154578',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '1',
            ),
            34 => 
            array (
              0 => 'trillodenis@hotmail.com',
              1 => 'Gutierrez',
              2 => 'Denis',
              3 => 'Diaz',
              4 => '2020-0035',
              5 => '09653265874',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '1',
            ),
            35 => 
            array (
              0 => 'cruzelmer@hotmail.com',
              1 => 'Cruz',
              2 => 'Elmer',
              3 => 'Hernandez',
              4 => '2020-0036',
              5 => '09682351547',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '2',
            ),
            36 => 
            array (
              0 => 'dela cruzandy@hotmail.com',
              1 => 'Dela Cruz',
              2 => 'Andy',
              3 => 'Tolentino',
              4 => '2020-0037',
              5 => '09653267874',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '5',
            ),
            37 => 
            array (
              0 => 'vera cruzelvira@hotmail.com',
              1 => 'Vera Cruz',
              2 => 'Elvira',
              3 => 'Valdez',
              4 => '2020-0038',
              5 => '09785484546',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            38 => 
            array (
              0 => 'alonzoalmira@hotmail.com',
              1 => 'Alonzo',
              2 => 'Almira',
              3 => 'Ramirez',
              4 => '2020-0039',
              5 => '09656586525',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            39 => 
            array (
              0 => 'geronimoclarence@hotmail.com',
              1 => 'Geronimo',
              2 => 'Clarence',
              3 => 'Morales',
              4 => '2020-0040',
              5 => '09322352365',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            40 => 
            array (
              0 => 'casabuenaglenn@hotmail.com',
              1 => 'Casabuena',
              2 => 'Glenn',
              3 => 'Mercado',
              4 => '2020-0041',
              5 => '09874564568',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            41 => 
            array (
              0 => 'almarantedwayne@hotmail.com',
              1 => 'Almarante',
              2 => 'Dwayne',
              3 => 'Tan',
              4 => '2020-0042',
              5 => '09853216985',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            42 => 
            array (
              0 => 'almodovargwen@hotmail.com',
              1 => 'Almodovar',
              2 => 'Gwen',
              3 => 'Aguilar',
              4 => '2020-0043',
              5 => '09451254587',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            43 => 
            array (
              0 => 'carascocharmaine@hotmail.com',
              1 => 'Carasco',
              2 => 'Charmaine',
              3 => 'Navarro',
              4 => '2020-0044',
              5 => '09632154879',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '6',
            ),
            44 => 
            array (
              0 => 'de mesahernan@hotmail.com',
              1 => 'De Mesa',
              2 => 'Hernan',
              3 => 'Bolor',
              4 => '2020-0045',
              5 => '09852584652',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '2',
              13 => '11',
            ),
            45 => 
            array (
              0 => 'piodenajoshua@hotmail.com',
              1 => 'Piodena',
              2 => 'Joshua',
              3 => 'Manalo',
              4 => '2020-0046',
              5 => '09153571598',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '11',
            ),
            46 => 
            array (
              0 => 'pabonjennie@hotmail.com',
              1 => 'Pabon',
              2 => 'Jennie',
              3 => 'Basbas',
              4 => '2020-0047',
              5 => '09651367895',
              6 => 'F',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '2',
            ),
            47 => 
            array (
              0 => 'calinajoseph@hotmail.com',
              1 => 'Calina',
              2 => 'Joseph',
              3 => 'Gomez',
              4 => '2020-0048',
              5 => '09357531596',
              6 => 'M',
              7 => 'MARRIED',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '3',
            ),
            48 => 
            array (
              0 => 'batitislucas@hotmail.com',
              1 => 'Batitis',
              2 => 'Lucas',
              3 => 'Dizon',
              4 => '2020-0049',
              5 => '09753571596',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '2',
              13 => '6',
            ),
            49 => 
            array (
              0 => 'de limamatthew@hotmail.com',
              1 => 'De Lima',
              2 => 'Matthew',
              3 => 'Del Rosario',
              4 => '2020-0050',
              5 => '09851234576',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '0',
              11 => '0',
              12 => '1',
              13 => '1',
            ),
            50 => 
            array (
              0 => 'pangilinanfreddie@hotmail.com',
              1 => 'Pangilinan',
              2 => 'Freddie',
              3 => 'Javier',
              4 => '2020-0051',
              5 => '09356541598',
              6 => 'M',
              7 => 'SINGLE',
              8 => 'FILIPINO',
              9 => '1',
              10 => '1',
              11 => '1',
              12 => '1',
              13 => '2',
            ),
        );

        unset($data[0]);

        foreach($data as $value)
        {
            $existing = User::where('email', $value[0])->first();
            if(!$existing) {
                $existing = User::where('code', $value[4])->first();
            }

            if(!$existing)
            {
                $user = new User;

                $user->email = $value[0];
                $user->password = Hash::make(Str::random(8));
                $user->profile_photo_path = $value[4] . '.png';
                $user->last_name = $value[1];
                $user->first_name = $value[2];
                $user->middle_name = $value[3];
                $user->code = $value[4];
                $user->phone_number = $value[5];
                $user->gender = $value[6] == 'M' ? 0 : 1;
                $user->marital_status = $value[7] == 'SINGLE' ? 0 : 1;
                $user->nationality = $value[8];
                $user->employment_status = $value[9];
                $user->is_paid_holidays = $value[10];
                $user->is_tax_exempted = $value[11];
                $user->is_tax_exempted = $value[11];
                $user->frequency_id = $value[12];
                $user->save();

                $designation_user = DB::table('designation_user')
                ->insert(['user_id'=>$user->id, 'designation_id' => $value[13]]);
            }
            
        }
    }
}
